Added bash comments ES translation
bobbyiliev/introduction-to-bash-scripting pull request #78
Opened 2022-10-05 03:17 UTC by ezerw

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Description
Spanish Translation of "Bash comments".

## Related Tickets & Documents
No related ticket or document. Spanish Translation of [ebook/en/006-bash-comments.md](https://github.com/bobbyiliev/introduction-to-bash-scripting/blob/main/ebook/en/content/006-bash-comments.md)

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2022-10-05 10:09 UTC, marcelozarate commented
Spanish translation so far uses formal tone (usted). Can you please adapt it?

2022-10-05 10:12 UTC, marcelozarate requested changes
I left you some suggestions, hope you don't mind 👌

2022-10-05 10:12 UTC, marcelozarate commented on ebook/es/content/006-bash-comments.md
> +Como con cualquier otro lenguaje de programación, puedes agregar comentarios a tu script. Los comentarios son usados para dejar notas personales en el código.
```suggestion
Como con cualquier otro lenguaje de programación, puede agregar comentarios a su script. Los comentarios son usados para dejar notas personales en el código.
```

2022-10-05 10:12 UTC, marcelozarate commented on ebook/es/content/006-bash-comments.md
> +Para hacerlo en Bash, necesitas agregar el simbolo `#` al comienzo de la línea. Los comentarios nunca aparecerán en la pantalla.
```suggestion
Para hacerlo en Bash, necesita agregar el simbolo `#` al comienzo de la línea. Los comentarios nunca aparecerán en la pantalla.
```

2022-10-05 10:12 UTC, marcelozarate commented on ebook/es/content/006-bash-comments.md
> +read -p "¿Cuál es tu nombre? " name
```suggestion
read -p "¿Cuál es tu nombre? " nombre
```

The example so far in the book uses the variable in its spanish version.

2022-10-05 10:12 UTC, marcelozarate commented on ebook/es/content/006-bash-comments.md
> +echo "Bienvenido a DevDojo!"
```suggestion
echo "¡Bienvenido a DevDojo!"
```

2022-10-05 10:12 UTC, marcelozarate commented on ebook/es/content/006-bash-comments.md
> +Los comentarios son una excelente manera de describir algunas de las funciones más complejas directamente en tus scripts para que otras personas puedan orientarse en tu código con facilidad.
```suggestion
Los comentarios son una excelente manera de describir algunas de las funciones más complejas directamente en tus scripts para que otras personas puedan orientarse en su código con facilidad.
```

2022-10-05 20:24 UTC, ezerw commented
Sure, thanks for the suggestions I'll do 👍

2022-10-05 20:47 UTC, ezerw commented
Done, please let me know if I miss something.

2022-10-06 10:09 UTC, marcelozarate commented on ebook/es/content/006-bash-comments.md
> +# Pregúntale al usuario su nombre
```suggestion
# Pregúntele al usuario su nombre
```

2022-10-06 19:49 UTC, ezerw commented
Good catch, that should be it then!

2022-10-07 09:26 UTC, bobbyiliev approved these changes
Thank you! This is just amazing!

2022-10-07 09:27 UTC, merged